In [1]:
import sys
sys.path.append('../../../')
from config import DATA_PATH, COCO_CAPTIONS_PATH
import json
import os
COCO_PATH = DATA_PATH + '/coco/'
from coco_captions import COCOCaptions

In [4]:
os.getcwd()

'/Users/timcares/CompSci/Uni/Projects/MasterThesis/src/datasets/coco'

In [2]:
with open(COCO_CAPTIONS_PATH+'dataset_coco.json') as f:
    data = json.load(f)

In [3]:
n_images ={
    'train':0,
    'restval':0,
    'val':0,
    'test':0
}

In [4]:
for d in data['images']:
    n_images[d['split']] += 1

In [5]:
n_images

{'train': 82783, 'restval': 30504, 'val': 5000, 'test': 5000}

In [6]:
for i in range(len(data['images'])):
    if data['images'][i]['split'] == 'restval':
        data['images'][i]['split'] = 'train'

In [7]:
n_images ={
    'train':0,
    'restval':0,
    'val':0,
    'test':0
}

In [8]:
for d in data['images']:
    n_images[d['split']] += 1

In [9]:
n_images

{'train': 113287, 'restval': 0, 'val': 5000, 'test': 5000}

In [10]:
for i in range(len(data['images'])):
    data['images'][i]['full_path'] = os.path.join(data['images'][i]['filepath'], data['images'][i]['filename'])

In [11]:
with open(COCO_PATH+'dataset_coco_karpathy.json', 'w') as f:
    json.dump(data, f)

In [13]:
with open(COCO_PATH+'dataset_coco_karpathy.json') as f:
    data = json.load(f)

In [7]:
os.mkdir(COCO_PATH+'karpathy_train')
os.mkdir(COCO_PATH+'karpathy_test')
os.mkdir(COCO_PATH+'karpathy_val')

In [13]:
for d in data['images']:
    os.symlink(COCO_PATH+d['full_path'], COCO_PATH+'karpathy_'+d['split']+'/'+d['filename'])

In [14]:
data=data['images']

In [15]:
meta_data = []
for meta_for_example in data:
    if meta_for_example['split'] == 'train':
        meta_for_example['full_path'] = os.path.abspath(meta_for_example['full_path'])
        meta_data.append(meta_for_example)
meta_data

[{'filepath': 'val2014',
  'sentids': [681330, 686718, 688839, 693159, 693204],
  'filename': 'COCO_val2014_000000522418.jpg',
  'imgid': 1,
  'split': 'train',
  'sentences': [{'tokens': ['a',
     'woman',
     'wearing',
     'a',
     'net',
     'on',
     'her',
     'head',
     'cutting',
     'a',
     'cake'],
    'raw': 'A woman wearing a net on her head cutting a cake. ',
    'imgid': 1,
    'sentid': 681330},
   {'tokens': ['a',
     'woman',
     'cutting',
     'a',
     'large',
     'white',
     'sheet',
     'cake'],
    'raw': 'A woman cutting a large white sheet cake.',
    'imgid': 1,
    'sentid': 686718},
   {'tokens': ['a',
     'woman',
     'wearing',
     'a',
     'hair',
     'net',
     'cutting',
     'a',
     'large',
     'sheet',
     'cake'],
    'raw': 'A woman wearing a hair net cutting a large sheet cake.',
    'imgid': 1,
    'sentid': 688839},
   {'tokens': ['there',
     'is',
     'a',
     'woman',
     'that',
     'is',
     'cutting',
   

In [18]:
meta_data[0]['sentences']

[{'tokens': ['a',
   'woman',
   'wearing',
   'a',
   'net',
   'on',
   'her',
   'head',
   'cutting',
   'a',
   'cake'],
  'raw': 'A woman wearing a net on her head cutting a cake. ',
  'imgid': 1,
  'sentid': 681330},
 {'tokens': ['a', 'woman', 'cutting', 'a', 'large', 'white', 'sheet', 'cake'],
  'raw': 'A woman cutting a large white sheet cake.',
  'imgid': 1,
  'sentid': 686718},
 {'tokens': ['a',
   'woman',
   'wearing',
   'a',
   'hair',
   'net',
   'cutting',
   'a',
   'large',
   'sheet',
   'cake'],
  'raw': 'A woman wearing a hair net cutting a large sheet cake.',
  'imgid': 1,
  'sentid': 688839},
 {'tokens': ['there',
   'is',
   'a',
   'woman',
   'that',
   'is',
   'cutting',
   'a',
   'white',
   'cake'],
  'raw': 'there is a woman that is cutting a white cake',
  'imgid': 1,
  'sentid': 693159},
 {'tokens': ['a',
   'woman',
   'marking',
   'a',
   'cake',
   'with',
   'the',
   'back',
   'of',
   'a',
   'chefs',
   'knife'],
  'raw': "A woman marking a 

In [2]:
from fairseq.tasks.masked_lm import MaskedLMConfig, MaskedLMTask

/Users/timcares/CompSci/Uni/Projects/MasterThesis/src/fairseq/fairseq/tasks/multires_hubert_pretraining.py:154: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  dictionaries = [ (Dictionary.load(f"{label_dir}/dict.{label}.txt") if label is not "" else None ) for label in self.cfg.labels]


In [3]:
config_data ={
    'data': COCO_PATH,
    'sample_break_mode': 'none',
    'tokens_per_sample': 512,
    'include_target_tokens': True,
    'random_token_prob': 0,
    'leave_unmasked_prob': 0,
    'include_index': True,
    'skip_masking': True,
    'd2v2_multi': True,
    'seed':42
}

In [4]:
config = MaskedLMConfig(**config_data)

In [14]:
config.shorten_method

'none'

In [14]:
task = MaskedLMTask.setup_task(config)

INFO:fairseq.tasks.masked_lm:dictionary: 50264 types


In [15]:
task.load_dataset(split='test')

INFO:fairseq.data.data_utils:loaded 30,100 examples from: /Users/timcares/CompSci/Uni/Projects/MasterThesis/data/coco/test
INFO:fairseq.tasks.masked_lm:loaded 641 blocks from: /Users/timcares/CompSci/Uni/Projects/MasterThesis/data/coco/test


In [26]:
task.datasets['test'][0].keys()

odict_keys(['id', 'net_input.source', 'net_input.id', 'net_input.padding_mask', 'nsentences', 'ntokens'])

In [31]:
task.datasets['test'][0]['net_input.padding_mask']

tensor([False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, 

In [2]:
mask_args = {}
ds = COCOCaptions(
    root=COCO_CAPTIONS_PATH,
    split='train',
    input_size=224,
    local_cache_path=None,
    key='imgs',
    beit_transforms=False,
    no_transform=False,
    compute_mask=True,
    crop_scale=(0.6, 1.0),
    **mask_args,
)

INFO:coco_captions:initial transform: Compose(
      RandomResizedCrop(size=(224, 224), scale=(0.6, 1.0), ratio=(0.75, 1.3333333333333333), interpolation=3, antialias=True)
      RandomHorizontalFlip(p=0.5)
), jitter transform: None, final transform: Compose(
      ToDtype(scale=True)
      Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225], inplace=False)
)
INFO:coco_captions:loaded 113287 examples


In [3]:
b=ds.collater([ds[i] for i in range(2)])

In [8]:
b['net_input']['teacher']

tensor([[    0,    32,  2415, 18730,   257, 12187,   351,   262,   736,   286,
           257, 21221,   338,  9845,    13],
        [    0,    32,  1862,  2933, 38806,   510,   379,   262,  3644,  5671,
            13,     1,     1,     1,     1]])

In [9]:
b['net_input']['padding_mask']

tensor([[False, False, False, False, False, False, False, False, False, False,
         False, False, False, False, False],
        [False, False, False, False, False, False, False, False, False, False,
         False,  True,  True,  True,  True]])

In [11]:
b['net_input']['precomputed_mask'].shape

torch.Size([2, 196])

In [13]:
b['net_input']['student'].shape

torch.Size([2, 3, 224, 224])