In [1]:
from transformers import BertTokenizer, BertModel, utils
import torch
from bertviz.neuron_view import show
from bertviz import model_view
utils.logging.set_verbosity_error()  # Suppress standard warnings

In [2]:
tokenizer:BertTokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased', output_attentions=True)

In [3]:
input_text_short = "a dog"
input_text_long = "a dog is playing in the garden with a tennis ball"

In [17]:
inputs = tokenizer.encode(input_text_long, return_tensors='pt')  # Tokenize input text
inputs

tensor([[ 101, 1037, 3899, 2003, 2652, 1999, 1996, 3871, 2007, 1037, 5093, 3608,
          102]])

In [7]:
attention_mask = torch.Tensor([[1,1,1,1,0, 1,0,0,1,1,1,0,1]])
attention_mask

tensor([[1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.]])

In [11]:
tokenizer.mask_token_id

103

In [18]:
inputs[0] = inputs[0]*attention_mask[0]+tokenizer.mask_token_id*(1-attention_mask[0])
inputs

tensor([[ 101, 1037, 3899, 2003,  103, 1999,  103,  103, 2007, 1037, 5093,  103,
          102]])

In [6]:
tokenizer.convert_ids_to_tokens(inputs[0])

['[CLS]',
 'a',
 'dog',
 'is',
 'playing',
 'in',
 'the',
 'garden',
 'with',
 'a',
 'tennis',
 'ball',
 '[SEP]']

In [19]:
#inputs = tokenizer.encode(input_text_short, return_tensors='pt')  # Tokenize input text
with torch.no_grad():
    outputs = model(inputs, attention_mask=attention_mask, output_attentions=True)  # Run model
attention = outputs[-1]  # Retrieve attention from model outputs
tokens = tokenizer.convert_ids_to_tokens(inputs[0])  # Convert input ids to token strings
model_view(attention, tokens, display_mode="light")  # Display model view

<IPython.core.display.Javascript object>

In [5]:
inputs = tokenizer.encode(input_text_long, return_tensors='pt')  # Tokenize input text
with torch.no_grad():
    outputs = model(inputs, output_attentions=True)  # Run model
attention = outputs[-1]  # Retrieve attention from model outputs
tokens = tokenizer.convert_ids_to_tokens(inputs[0])  # Convert input ids to token strings
model_view(attention, tokens, display_mode="light")  # Display model view

<IPython.core.display.Javascript object>