In [3]:
import torch
import math

In [2]:
df = lambda x1, y1, x2, y2: abs(x1 - x2) + abs(y1 - y2)

In [21]:
max_positions=4

In [17]:
pos_bias = torch.zeros((max_positions, max_positions))
n=int(math.sqrt(max_positions))
for i in range(n):
    for j in range(n):
        for k in range(n):
            for l in range(n):
                new_x = i * n + j
                new_y = k * n + l
                pos_bias[new_x, new_y] = -df(i, j, k, l)

In [18]:
pos_bias

tensor([[ 0., -1., -2., -3., -1., -2., -3., -4., -2., -3., -4., -5., -3., -4.,
         -5., -6.],
        [-1.,  0., -1., -2., -2., -1., -2., -3., -3., -2., -3., -4., -4., -3.,
         -4., -5.],
        [-2., -1.,  0., -1., -3., -2., -1., -2., -4., -3., -2., -3., -5., -4.,
         -3., -4.],
        [-3., -2., -1.,  0., -4., -3., -2., -1., -5., -4., -3., -2., -6., -5.,
         -4., -3.],
        [-1., -2., -3., -4.,  0., -1., -2., -3., -1., -2., -3., -4., -2., -3.,
         -4., -5.],
        [-2., -1., -2., -3., -1.,  0., -1., -2., -2., -1., -2., -3., -3., -2.,
         -3., -4.],
        [-3., -2., -1., -2., -2., -1.,  0., -1., -3., -2., -1., -2., -4., -3.,
         -2., -3.],
        [-4., -3., -2., -1., -3., -2., -1.,  0., -4., -3., -2., -1., -5., -4.,
         -3., -2.],
        [-2., -3., -4., -5., -1., -2., -3., -4.,  0., -1., -2., -3., -1., -2.,
         -3., -4.],
        [-3., -2., -3., -4., -2., -1., -2., -3., -1.,  0., -1., -2., -2., -1.,
         -2., -3.],
        [-

In [15]:
pos_bias.unsqueeze(0).expand(8, -1, -1).shape

torch.Size([8, 4, 4])

In [22]:
pos_bias = (
            torch.abs(
                torch.arange(max_positions).unsqueeze(0) - torch.arange(max_positions).unsqueeze(1)
            )
            * -1
        )

In [23]:
pos_bias.repeat(bn, 1, 1)

tensor([[ 0, -1, -2, -3],
        [-1,  0, -1, -2],
        [-2, -1,  0, -1],
        [-3, -2, -1,  0]])

In [26]:
def get_slopes_power_of_2(n):
    start = 2 ** (-(2 ** -(math.log2(n) - 3)))
    ratio = start
    return [start * ratio**i for i in range(n)]

In [31]:
torch.tensor(get_slopes_power_of_2(8)).unsqueeze(1).unsqueeze(1)

tensor([[[0.5000]],

        [[0.2500]],

        [[0.1250]],

        [[0.0625]],

        [[0.0312]],

        [[0.0156]],

        [[0.0078]],

        [[0.0039]]])

In [37]:
torch.full(
            (
                (5 + 5),
                1,
                2,
                1,
                1,
            ),
            1.0,
            dtype=torch.float,
        ).clamp_min(0)

tensor([[[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]],



        [[[[1.]],

          [[1.]]]]])