In [1]:
from validate import ZeroShotCallback
from multimodal_data2vec import KDMMData2Vec, KDMMData2VecConfig

/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File 

In [1]:
from datamodules import IMDBDataModule, SpeechCommandsDataModule, CIFARDataModule, OpenWebTextDataModule, LibriSpeechDataModule

/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Us

In [2]:
ds = LibriSpeechDataModule(data_path='../data',
                           sample_rate=16000,
                           max_sample_size=320000,
                           min_sample_size=32000,
                           # precompute_mask_config={
                           #     'feature_encoder_spec': '[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] + [(512,2,2)]',
                           # },
                           precompute_mask_config=None,
                           types_train=('train-clean-100',),
                           types_test=('test-clean',),
                           normalize=True,
                           pad=True,
                           batch_size=512,
                           num_workers=4,
                           shuffle=False,
                           drop_last=False,)

In [3]:
ds.prepare_data()

In [4]:
ds.setup('fit')

INFO:fairseq.data.audio.raw_audio_dataset:loaded 28515, skipped 24 samples


In [5]:
dl = ds.train_dataloader()
dl_iter = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [6]:
b = next(dl_iter)
b

{'id': tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174, 17

In [9]:
b['audio'].shape

torch.Size([512, 270560])

In [3]:
ds = OpenWebTextDataModule(data_path='../data', num_max_bpe_tokens=512, sample_break_mode='none',
                           batch_size=512, num_workers=1, shuffle=False, drop_last=False)

In [4]:
ds.prepare_data()

INFO:datasets_.base_datasets:[OpenWebTextDataset]: Found 2 tar files, inflating...
INFO:datasets_.base_datasets:[OpenWebTextDataset]: Inflated all tar files.
INFO:datasets_.base_datasets:[OpenWebTextDataset]: Cleaning...
INFO:datasets_.base_datasets:[OpenWebTextDataset]: Joining...
INFO:datasets_.base_datasets:[OpenWebTextDataset]: Encoding...
processed 10000 lines
processed 20000 lines
processed 30000 lines
processed 40000 lines
processed 50000 lines
processed 60000 lines
processed 70000 lines
processed 80000 lines
processed 90000 lines
processed 100000 lines
processed 110000 lines
processed 120000 lines
processed 130000 lines
processed 140000 lines
processed 150000 lines
processed 160000 lines
processed 170000 lines
processed 180000 lines
processed 190000 lines
processed 200000 lines
processed 210000 lines
processed 220000 lines
processed 230000 lines
processed 240000 lines
processed 250000 lines
processed 260000 lines
processed 270000 lines
processed 280000 lines
processed 290000 li

In [5]:
ds.setup('fit')

INFO:fairseq.data.data_utils:loaded 15,496,691 examples from: ../data/language/openwebtext/train
INFO:datasets_.base_datasets:loaded 2791909 blocks from: ../data/language/openwebtext/train


In [5]:
ds.setup('fit')

INFO:fairseq.data.data_utils:loaded 14,726,625 examples from: ../data/language/openwebtext/train
INFO:datasets_.base_datasets:loaded 1517093 blocks from: ../data/language/openwebtext/train


In [6]:
dl=ds.train_dataloader()

In [29]:
len(dl)

2964

In [7]:
len(dl)*2/1e3

5.928

In [8]:
it = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [48]:
b=next(it)
b

OrderedDict([('text',
              tensor([[    0, 50108, 50108,  ...,   232,  6281,     2],
                      [    0,  2046,    14,  ..., 27430,     8,     2],
                      [    0,   633,  2687,  ..., 50108, 50108,     2],
                      ...,
                      [    0, 50108, 50108,  ..., 50108, 50108,     2],
                      [    0, 50108, 50108,  ...,  3804,  2357,     2],
                      [    0,  8862,     6,  ..., 50108, 50108,     2]])),
             ('padding_mask',
              tensor([[False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      ...,
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False]])),
             ('id',
    

In [28]:
b=next(it)
b

OrderedDict([('text',
              tensor([[    0,     9,  1191,  ...,    14,   472,     2],
                      [    0,    23,   430,  ...,    21,   309,     2],
                      [    0,     7, 15499,  ...,  4536,  5986,     2],
                      ...,
                      [    0,     4,     2,  ...,  2217,   258,     2],
                      [    0,  8333,    30,  ...,   145,     5,     2],
                      [    0, 17032,  9953,  ...,    71,  2086,     2]])),
             ('padding_mask',
              tensor([[False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      ...,
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False],
                      [False, False, False,  ..., False, False, False]])),
             ('id',
    

In [13]:
1.0906e-05

1.0906e-05

In [9]:
5453*512

2791936

In [3]:
ds = SpeechCommandsDataModule(data_path='../data',
                              min_sample_size=0,
                              normalize=True,
                              pad=True,
                              batch_size=512,
                              num_workers=5,
                              shuffle=False,
                              drop_last=False)

In [4]:
callback = ZeroShotCallback(n_neighbors=20, datamodules={'imdb': ds}, data_path='../data',
                            num_max_bpe_tokens=512, is_multimodal_aligned=False)

In [5]:
cfg = KDMMData2VecConfig(
    depth=1,
    num_heads=12,
    mlp_ratio=0.1)

In [6]:
model = KDMMData2Vec(cfg=cfg)

INFO:multimodal_data2vec:Loading modality encoder for: Modality.AUDIO
INFO:utils:Modality used: Modality.AUDIO
INFO:data2vec_fairseq.models.data2vec2:making target model
/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/nn/modules/module.py:1877: UserWarning: Positional args are being deprecated, use kwargs instead. Refer to https://pytorch.org/docs/master/generated/torch.nn.Module.html#torch.nn.Module.state_dict for details.
  warnings.warn(
INFO:utils:Loaded state dict, result: <All keys matched successfully>
INFO:multimodal_data2vec:Loading modality encoder for: Modality.IMAGE
INFO:utils:Modality used: Modality.IMAGE
INFO:data2vec_fairseq.models.data2vec2:making target model
INFO:utils:Loaded state dict, result: <All keys matched successfully>
INFO:multimodal_data2vec:Loading modality encoder for: Modality.TEXT
INFO:utils:Modality used: Modality.TEXT
INFO:data2vec_fairseq.models.data2vec2:making target model
INFO:utils:Loaded state dict, result: <All keys matc

In [7]:
from types import SimpleNamespace
d = {'model': model, 'device':'cpu'}
pl_module =  SimpleNamespace(**d)

In [8]:
_, result = callback.on_validation_start(trainer=None, pl_module=pl_module)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl_/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._nam