In [1]:
from datamodules import KDDataModule, DummyDataModule

/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Us

In [2]:
dm = DummyDataModule()

In [3]:
dm.prepare_data()

In [4]:
dm.setup('fit')
dm.setup('test')

In [5]:
dl = dm.train_dataloader()

In [6]:
iter_dl = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [11]:
next(iter_dl).shape

torch.Size([64, 512, 786])

In [1]:
import torch

In [4]:
m=torch.load('mask.pt')

In [6]:
m.mask.bool()

tensor([[False, False, False,  ..., False, False, False],
        [False, False,  True,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [43]:
p=torch.load('padding_mask.pt')
p

tensor([[False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ...,  True,  True,  True],
        [False, False, False,  ...,  True,  True,  True]])

In [10]:
~p.bool()

tensor([[ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ...,  True,  True,  True],
        [ True,  True,  True,  ..., False, False, False],
        [ True,  True,  True,  ..., False, False, False]])

In [56]:
(p[:, 0].sum()==0).item()

True

In [50]:
y=torch.rand((5, 820, 768))
y.shape

torch.Size([5, 820, 768])

In [23]:
y[0].shape

torch.Size([820, 768])

In [25]:
p[0].shape

torch.Size([820])

In [51]:
non_padded_avg = []
for i in range(y.size(0)):
    non_padded_avg.append(y[i][~p[i]].mean(dim=0)) # list of B*(tensors of shape (C,))
y = torch.stack(non_padded_avg) # list of B*(tensors of shape (C,)) -> BC

In [53]:
y.shape

torch.Size([5, 768])

In [9]:
r=torch.load('../data/kd_openwebtext/0_0-255.pt')

In [4]:
r.keys()

dict_keys(['target', 'text', 'modes', 'padding_mask'])

In [5]:
stacked=torch.stack(r['target']['layer_results'], dim=-1)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [10]:
r['target']['layer_results'].shape

torch.Size([12, 256, 768])

In [23]:
stacked.shape

torch.Size([12, 256, 512, 768])

In [2]:
ds = KDOpenWebTextDataset(data_path='../data')

In [3]:
ds.load()

In [4]:
b=ds.collater(ds[0])

In [5]:
b

{'label': tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174,

In [3]:
dm = KDDataModule(data_path='../data', num_workers=5, dataset='openwebtext')

In [4]:
dm.prepare_data()

In [5]:
dm.setup(stage='fit')

In [6]:
dl = dm.train_dataloader()

In [7]:
dl_iter = iter(dl)

In [8]:
batch = next(dl_iter)

In [10]:
batch

{'label': tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174,

In [12]:
batch['source']

tensor([[    0, 13632,   763,  ...,   104,     4,     2],
        [    0,  1659,   641,  ..., 50108,  2663,     2],
        [    0,  3706,  2022,  ...,    17,    46,     2],
        ...,
        [    0, 50108, 50108,  ..., 50108, 50108,     2],
        [    0, 50108, 50108,  ...,  1439, 14236,     2],
        [    0,   201,    14,  ..., 50108, 50108,     2]])