In [1]:
from datamodules import OpenWebTextDataModule, LibriSpeechDataModule
import torch

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [114]:
t = torch.ones(2, 3, 4)
t

tensor([[[0.0394, 0.6236, 0.5217, 0.2288],
         [0.0671, 0.9122, 0.4706, 0.0772],
         [0.2851, 0.9208, 0.3762, 0.9986]],

        [[0.4197, 0.2042, 0.3527, 0.1137],
         [0.9975, 0.8041, 0.6005, 0.2652],
         [0.5677, 0.4694, 0.8450, 0.8799]]])

In [1]:
from datamodules import QQPDataModule

In [4]:
d = QQPDataModule(data_path='../data', num_max_bpe_tokens=512,
                  batch_size=512, num_workers=1, shuffle=False, drop_last=False)

In [5]:
d.prepare_data()

INFO:datasets:PyTorch version 2.2.2 available.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): qim.fs.quoracdn.net:80
DEBUG:urllib3.connectionpool:http://qim.fs.quoracdn.net:80 "GET /quora_duplicate_questions.tsv HTTP/1.1" 301 167
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): qim.fs.quoracdn.net:443
DEBUG:urllib3.connectionpool:https://qim.fs.quoracdn.net:443 "GET /quora_duplicate_questions.tsv HTTP/1.1" 200 58176133
INFO:datasets_.data_utils:Write ../data/qqp/train.jsonl with 50000 items !
/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torchdata/datapipes/iter/util/cacheholder.py:434: UserWarning: Attempt to mark ../data/qqp/datasets/QQP/quora_duplicate_questions.tsv.promise.9af1b409-c661-49c4-a8f1-30af66120ba6 promise (base of file ../data/qqp/datasets/QQP/quora_duplicate_questions.tsv) as fulfilled failed. Potentially missmatching filename functions of on_disk_cache and end_cache.
  warnings.warn(


In [6]:
d.setup('fit')

INFO:datasets_.base_datasets:[QQPDataset]: Load 50000 text examples.


In [7]:
dl = d.train_dataloader()

In [8]:
dl_iter = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [9]:
b = next(dl_iter)
b

{'text0': tensor([[    0,  2061,   318,  ...,     1,     1,     1],
         [    0,  2061,   318,  ...,     1,     1,     1],
         [    0,  2437,   460,  ...,     1,     1,     1],
         ...,
         [    0,  2437,   857,  ...,     1,     1,     1],
         [    0, 13921,  3012,  ...,     1,     1,     1],
         [    0,  2437,  1327,  ...,     1,     1,     1]]),
 'padding_mask0': tensor([[0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         ...,
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1]]),
 'text1': tensor([[    0,  2061,   318,  ...,     1,     1,     1],
         [    0,  2061,   561,  ...,     1,     1,     1],
         [    0,  2437,   460,  ...,     1,     1,     1],
         ...,
         [    0, 13921,  1005,  ...,     1,     1,     1],
         [    0,  2437,   460,  ...,     1,     1,     1],
         [    0,  5195,   750,  ...,     1,     1,     1]]),

In [115]:
import torch.nn.functional as F

In [140]:
torch.nn.LayerNorm(4)(t)

tensor([[[-1.3526,  1.1644,  0.7251, -0.5369],
         [-0.9073,  1.5296,  0.2560, -0.8783],
         [-1.1346,  0.8684, -0.8473,  1.1136]],

        [[ 1.2215, -0.5677,  0.6653, -1.3191],
         [ 1.2198,  0.5064, -0.2447, -1.4816],
         [-0.6982, -1.2570,  0.8783,  1.0769]]],
       grad_fn=<NativeLayerNormBackward0>)

In [146]:
F.normalize(t[0][0].unsqueeze(0),dim=-1)

tensor([[0.0467, 0.7376, 0.6170, 0.2706]])

In [134]:
r=F.layer_norm(t, normalized_shape=(3, 4))
r

tensor([[[-1.2748,  0.4956,  0.1866, -0.7011],
         [-1.1910,  1.3702,  0.0317, -1.1605],
         [-0.5305,  1.3961, -0.2542,  1.6320]],

        [[-0.4473, -1.2270, -0.6897, -1.5544],
         [ 1.6435,  0.9438,  0.2071, -1.0061],
         [ 0.0882, -0.2674,  1.0915,  1.2179]]])

In [125]:
r.mean(dim=1)

tensor([[-0.9988,  1.0873, -0.0120, -0.0765],
        [ 0.4281, -0.1835,  0.2030, -0.4475]])

In [129]:
F.normalize(t, dim=-1)

tensor([[[0.0467, 0.7376, 0.6170, 0.2706],
         [0.0650, 0.8844, 0.4562, 0.0748],
         [0.1982, 0.6403, 0.2616, 0.6944]],

        [[0.7042, 0.3426, 0.5918, 0.1908],
         [0.6929, 0.5586, 0.4171, 0.1842],
         [0.3984, 0.3294, 0.5929, 0.6175]]])

In [10]:
dm = OpenWebTextDataModule(data_path='../data',
                           num_max_bpe_tokens=512,
                           sample_break_mode='none',
                           batch_size=256,
                           num_workers=1,
                           drop_last=True,
                           shuffle=True,)

In [27]:
dm = LibriSpeechDataModule(data_path='../data',
                           sample_rate=16000,
                           max_sample_size=320_000,
                           min_sample_size=0,
                           normalize=True,
                           pad=True,
                           types_train=['train-clean-100', 'test-other'],
                           batch_size=256,
                           num_workers=1,
                           drop_last=True,
                           shuffle=True,)

In [28]:
dm.prepare_data()

In [29]:
dm.setup('fit')

INFO:fairseq.data.audio.raw_audio_dataset:loaded 28539, skipped 0 samples
INFO:fairseq.data.audio.raw_audio_dataset:loaded 2939, skipped 0 samples


In [30]:
dl = dm.train_dataloader()

In [31]:
len(dl)

122

In [32]:
dl_iter = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [34]:
b=next(dl_iter)
b['audio']

tensor([[ 2.2359e-05,  2.2359e-05,  2.2359e-05,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 1.6583e-02,  1.7562e-02,  7.7667e-03,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-9.6405e-03, -1.2852e-02, -1.0443e-02,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [-5.0267e-02,  7.9174e-03,  4.8271e-02,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-1.9171e-02, -2.2060e-02, -2.8250e-02,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [-3.2774e-02, -3.2167e-02, -3.3381e-02,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]])

In [101]:
from utils import load_pretrained_d2v_model

In [102]:
model = load_pretrained_d2v_model('../models/nlp_base.pt')

INFO:utils:Modality used: Modality.TEXT
INFO:data2vec_fairseq.models.data2vec2:making target model
INFO:utils:Loaded state dict, result: <All keys matched successfully>


In [14]:
sd = torch.load('../models/nlp_base.pt')

In [11]:
sd['cfg']['model']['modalities']['image']['num_extra_tokens']

1

In [15]:
sd['cfg']['model']['modalities']['text']['num_extra_tokens']

0

In [13]:
sd['cfg']['model']['modalities']['audio']['num_extra_tokens']

0

In [17]:
b=torch.load('../data/kd_openwebtext/0_0-255.pt')
b.keys()

dict_keys(['target', 'text', 'modes'])

In [6]:
b['target'].shape

torch.Size([256, 2, 768])

In [2]:
from datamodules import IMDBDataModule
from datasets_ import ImageNetDataset

In [3]:
dm = IMDBDataModule(data_path='../data',
                    num_max_bpe_tokens=512,
                    batch_size=256,
                    num_workers=1,
                    drop_last=True,
                    shuffle=True,)

In [4]:
dm.prepare_data()

INFO:datasets:PyTorch version 2.2.2 available.
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ai.stanford.edu:80
DEBUG:urllib3.connectionpool:http://ai.stanford.edu:80 "GET /~amaas/data/sentiment/aclImdb_v1.tar.gz HTTP/1.1" 200 84125825
INFO:datasets_.data_utils:Write ../data/imdb/train.jsonl with 25000 items !
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ai.stanford.edu:80
DEBUG:urllib3.connectionpool:http://ai.stanford.edu:80 "GET /~amaas/data/sentiment/aclImdb_v1.tar.gz HTTP/1.1" 200 84125825
INFO:datasets_.data_utils:Write ../data/imdb/test.jsonl with 25000 items !


In [6]:
dm.setup('fit')

INFO:datasets_.base_datasets:[IMDBDataset]: Load 25000 text examples.


In [7]:
dl = dm.train_dataloader()

In [8]:
iter_dl = iter(dl)

DEBUG:torio._extension.utils:Loading FFmpeg6
DEBUG:torio._extension.utils:Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torio/_extension/utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/site-packages/torch/_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "/Users/timcares/miniconda3/envs/mmrl/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mo

In [9]:
b=next(iter_dl)
b

{'text': tensor([[    0,  1212,  2646,  ...,   318,  2826,   503],
         [    0,    40,  7342,  ...,     1,     1,     1],
         [    0,    32,   649,  ...,   284,   257, 19207],
         ...,
         [    0,    40,  1422,  ...,     1,     1,     1],
         [    0,  9139,  3225,  ...,     1,     1,     1],
         [    0,  1212,   318,  ...,     1,     1,     1]]),
 'padding_mask': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1],
         [0, 0, 0,  ..., 1, 1, 1]]),
 'target': tensor([1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
         0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
         0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
         1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
         0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1

In [11]:
b['target'].sum()

tensor(128)

In [7]:
import torchtext
data_loader = iter(torchtext.datasets.IMDB(root='../data', split='train'))

In [8]:
it = iter(data_loader)

In [47]:
next(it)[0]-1

0

In [ ]:
ds = ImageNetDataset(data_path='/workspace/imagenet', split='train', 
                     beit_transforms=False,
                     no_transform=False,
                     transform_jitter=False,
                     crop_scale=(0.6, 1.0),
                     dataset_type='imagefolder',
                     local_cache_path=None,
                     precompute_mask_config=None,
                     return_path=False)

In [ ]:
ds.load()

In [24]:
target_layer_results=[torch.rand(12, 5, 16) for _ in range(10)]

In [25]:
target_layer_results = torch.stack(target_layer_results, dim=1)
target_layer_results = target_layer_results[:, :, 0, :]

In [27]:
target_layer_results.shape

torch.Size([12, 10, 16])

In [56]:
target_q = torch.Tensor([1,0,1])
target_mem = torch.Tensor([1,0,1,0,0])

In [31]:
sim=torch.Tensor([
    [0.1, 0.2, 0.5, 0.4, -0.1],
    [1.0, 0.9, 0.4, 0.5, 0.6],
    [0.5, 0.4, 0.5, -0.1, 0.7],
])
sim

tensor([[ 0.1000,  0.2000,  0.5000,  0.4000, -0.1000],
        [ 1.0000,  0.9000,  0.4000,  0.5000,  0.6000],
        [ 0.5000,  0.4000,  0.5000, -0.1000,  0.7000]])

In [108]:
sim.t()

tensor([[ 0.1000,  1.0000,  0.5000],
        [ 0.2000,  0.9000,  0.4000],
        [ 0.5000,  0.4000,  0.5000],
        [ 0.4000,  0.5000, -0.1000],
        [-0.1000,  0.6000,  0.7000]])

In [106]:
def _get_all_match(similarity_scores:torch.Tensor,
                   m_bank_targets:torch.Tensor,
                   q_targets:torch.Tensor,
                   k:int):
    
    _, indices = similarity_scores.topk(k, dim=-1)
    return (m_bank_targets[indices]==q_targets.unsqueeze(1)).all(dim=-1).sum().div(len(q_targets))


def unimodal_zero_shot_retrieval(similarity_scores, memory_bank_targets, query_targets) -> None:
    results = {}
    similarity_scores_t = similarity_scores.t()
    train_test_top1 = _get_all_match(similarity_scores, memory_bank_targets, query_targets, k=1)
    test_train_top1 = _get_all_match(similarity_scores_t, query_targets, memory_bank_targets, k=1)

    results[f"unimodal-retrieval--zeroshot-train-test-top1"] = train_test_top1.item()
    results[f"unimodal-retrieval--zeroshot-test-train-top1"] = test_train_top1.item()

    try:
        test_train_top5 = _get_all_match(similarity_scores_t, query_targets, memory_bank_targets, k=3)
        train_test_top5 = _get_all_match(similarity_scores, memory_bank_targets, query_targets, k=3)

        results[f"unimodal-retrieval--zeroshot-train-test-top5"] = train_test_top5.item()
        results[f"unimodal-retrieval--zeroshot-test-train-top5"] = test_train_top5.item()
    except:
        pass # if data has less than 5 classes, top5-accuracy will throw an error
    return results

In [107]:
unimodal_zero_shot_retrieval(sim, target_mem, target_q)

{'unimodal-retrieval--zeroshot-train-test-top1': 0.3333333432674408,
 'unimodal-retrieval--zeroshot-test-train-top1': 0.6000000238418579,
 'unimodal-retrieval--zeroshot-train-test-top5': 0.0,
 'unimodal-retrieval--zeroshot-test-train-top5': 0.0}

In [90]:
_, indices_top1 = sim.topk(1, dim=-1)
indices_top1 = indices_top1
indices_top1

tensor([[2],
        [0],
        [4]])

In [99]:
target_mem

tensor([1., 0., 1., 0., 0.])

In [91]:
target_mem[indices_top1]

tensor([[1.],
        [1.],
        [0.]])

In [92]:
target_q.unsqueeze(1)

tensor([[1.],
        [0.],
        [1.]])

In [95]:
target_mem[indices_top1]==target_q.unsqueeze(1)

tensor([[ True],
        [False],
        [False]])

In [96]:
(target_mem[indices_top1]==target_q.unsqueeze(1)).all(dim=-1).sum().div(len(target_q))

tensor(0.3333)

In [71]:
_, indices = sim.topk(3, dim=-1)
indices

tensor([[2, 3, 1],
        [0, 1, 4],
        [4, 2, 0]])

In [74]:
target_q

tensor([1., 0., 1.])

In [75]:
target_mem[indices]

tensor([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 1.]])

In [97]:
_, indices = sim.topk(3, dim=-1)
(target_mem[indices]==target_q.unsqueeze(1)).all(dim=-1).sum().div(len(target_q))

tensor(0.)